### ISSUE TITLE
Year layout bug

### ISSUE THREAD

**Issue by vlashton** [KylaBendrik/KingdomSim#45]
**Describe the bug**
The peeps/build menu gets bumped down when the years go into double digits.

**To Reproduce**
play to year 10

**Expected behavior**
The menu stays put no matter what year it is.

**Screenshots**

![year layout bug](https://user-images.githubusercontent.com/16104992/47685303-5fa05100-dbac-11e8-8601-fb3c800354f7.PNG)

**Desktop (please complete the following information):**

**Additional context**

**Comment by KylaBendrik** [comment]
Good catch! I'll get to work on that. :)
